CREATE OR REPLACE FUNCTION FN_TOTAL_DONORS RETURN NUMBER AS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM Donor;
    RETURN v_count;
END;
/

CREATE OR REPLACE FUNCTION FN_TOTAL_ORGANIZATIONS RETURN NUMBER AS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM Organization;
    RETURN v_count;
END;
/

CREATE OR REPLACE FUNCTION FN_TOTAL_REQUESTS RETURN NUMBER AS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM Request;
    RETURN v_count;
END;
/

CREATE OR REPLACE FUNCTION FN_SUCCESSFUL_TRANSACTIONS RETURN NUMBER AS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count 
    FROM Transaction_ 
    WHERE Status = 'Successful';
    
    RETURN v_count;
END;
/